import os

expanded_dataset = """label,text
ham,"Hey, are we still meeting for lunch at 1 PM today?"
spam,"URGENT! Your mobile number has been selected for a £2000 prize. Call 09061701461 now!"
ham,"I'm running a bit late, see you in fifteen minutes."
spam,"FREE ringtone! Reply with TONE to claim your complimentary gift right away."
ham,"Can you send me the notes from yesterday's history lecture?"
spam,"Congratulations! You have won a free tropical cruise vacation. Click here now!"
ham,"Let's catch up over the weekend, let me know when you are free."
spam,"Dear customer, your bank account has been locked. Verify your credentials at this link."
ham,"Don't forget to buy milk on your way home tonight."
spam,"Get rich quick! Earn $5000 a day working completely from home. No experience needed!"
ham,"Are you coming to the football match this evening?"
spam,"LOSE WEIGHT FAST! Magical new pill melts fat while you sleep. Order today!"
ham,"The project deadline has been extended to next Friday afternoon."
spam,"Double your bitcoins overnight guaranteed. Secure investments starting at $10."
ham,"Just checking in to see how your job interview went yesterday."
spam,"FINAL WARNING: Your package could not be delivered. Pay $2 re-delivery fee here."
ham,"I left my keys on your kitchen counter, could you check?"
spam,"Adult network matching. Meet singles in your area tonight! Reply STOP to optout."
ham,"Thanks for the birthday wishes, hope you are doing well!"
spam,"Claim your $500 Walmart gift card now by completing this short 2 minute survey."
ham,"Hey, what time does the movie start tonight? Let me know."
spam,"WINNER! As a valued subscriber you have been selected to receive a free iPad. Click here."
ham,"Can you pick up some grocery items on your way back from work?"
spam,"URGENT NOTICE: Your credit card account has suspicious activity. Log in immediately to verify."
ham,"I'll be home late tonight, don't wait up for dinner."
spam,"Hot single girls in your neighborhood are waiting for you! Text CHAT to 55555 now!"
ham,"Did you finish the financial report for the quarterly review?"
spam,"GUARANTEED income stream. Make thousands weekly processing simple emails from your bed."
ham,"Let's plan a hiking trip for this upcoming Sunday morning."
spam,"Your subscription has automatically renewed. Click here to cancel and claim your discount."
ham,"Could you please review the attached document and give me feedback?"
spam,"CASH PRIZE ALERT! You have won $10,000 in our annual sweepstakes lottery!"
ham,"Are we still on for our tennis match tomorrow evening?"
spam,"LOANS APPROVED INSTANTLY! No credit check required. Bad credit ok. Apply inside."
ham,"I missed the bus, can you please come and pick me up?"
spam,"REVEALED: The secret trick Wall Street doesn't want you to know to get rich!"
ham,"Thanks for inviting me to the party, I had a wonderful time!"
spam,"Your package is held at our distribution center. Confirm address details immediately."
ham,"Hi mom, I just wanted to call and check how you are feeling today."
spam,"CONGRATULATIONS! Your profile won a entry ticket to our exclusive matching portal."
ham,"Let's grab a coffee tomorrow afternoon and catch up properly."
spam,"Get cheap medications without a doctor prescription! Orders delivered discreetly overnight."
ham,"Can we reschedule our sync to Thursday morning instead?"
spam,"ALERT: Your utility bill payment failed. Pay now to avoid immediate power termination."
ham,"The weather looks beautiful today, want to go for a quick walk?"
spam,"Double your investment value in less than two weeks. Zero risk involved. Join now."
ham,"I just sent over the finalized contract files to your email inbox."
spam,"FREE entry into our weekly cash draw! Simply text WIN to 88221 to participate."
ham,"What do you want to order for dinner tonight? Pizza or Chinese?"
spam,"Exclusive luxury watch replica clearance sale! Up to 90% off retail pricing today."
ham,"Let me know when you are free to discuss the team restructuring."
spam,"You are pre-approved for a platinum reward card with zero interest. Sign up here."
ham,"I'm going to the gym now, talk to you later!"
spam,"Your iCloud storage is full. Access your account here to secure your personal photos."
ham,"Could you forward me the contact info for the new marketing consultant?"
spam,"Make your bank account grow while you sleep! Sign up for our automated trading bot."
ham,"I left my notebook in the conference room, did anyone see it?"
spam,"⚠️ Security Alert: An unauthorized device accessed your personal email account."
ham,"Let's meet at the usual restaurant at 7:30 PM tonight."
spam,"CLAIM NOW: Your complimentary shopping voucher is expiring in 24 hours. Act fast!"
"""

target_file_path = os.path.join("data", "raw", "spam.csv")
os.makedirs(os.path.dirname(target_file_path), exist_ok=True)

with open(target_file_path, "w", encoding="utf-8") as f:
    f.write(expanded_dataset.strip())

print("Success! Expanded offline vocabulary dataset generated inside data/raw/spam.csv.")
